package io.askhole

import kotlin.random.Random
import io.askhole.Question.Companion.QuestionType.*


class QuestionList {


    companion object {

        data class Q(val text: String, val type: Question.Companion.QuestionType)


        val questions = listOf(
            Q("At what age did you first begin experiencing existential or self-aware thoughts?",THOUGHTFUL),
            Q("A dragon demands a sacrifice. Either you can feed him a child, or your country can pool 1 trillion dollars to feed him instead. Which would you feed him?",THOUGHTFUL),
            Q("Your heart is failing and you need a new one. You have the ability to clone a healthy version of yourself, then before clone wakes up, kill him/her and take the heart. Do you do this?",THOUGHTFUL),
            Q("How do you personally know when something is immoral?",THOUGHTFUL),
            Q("If you could push a button and give everyone perfect understanding of what makes women attracted to men, would you press the button?",EDGY),
            Q("Would you rather hurt yourself or others?",SAD),
            Q("If you could press the button and get everything you wanted — no more hunger, no more pain (unless you want it), immediate wish fulfillment, immortality, with this power lasting for the rest of your existence — would you do it? Why or why not?",THOUGHTFUL),
            Q("Is incest wrong? Should it be illegal?",EDGY),
            Q("Is it okay to become aroused by fantasies of actions that would result in serious harm if done in real life?",EDGY),
            Q("Is sex really about power?",EDGY),
            Q("In one room, a child is about to die. In the other room, a demon is about to increase unemployment in your country by 1% for 3 years. You can either save the child or kill the demon, but not both. Which do you choose?",THOUGHTFUL),
            Q("You're in a monogamous relationship. Your partner gets back late and says \"Honey, I just had sex with the new lifelike sex robot.\" Is this cheating?",THOUGHTFUL),
            Q("Which political party do you most identify with?",EDGY),
            Q("Do you ever feel guilt or shame for romantically rejecting people who are interested in you?",SAD),
            Q("Assuming everyone you met were interested in having sex with you, what percentage of them would you accept?",SEXY),
            Q("It is before your birth, and you are standing in front of a vast wall of books. Each book is a character - less so the 'story' of the life, but more their values and traits. What sort of character do you choose to be?",THOUGHTFUL),
            Q("You’ve caught a man who knows the location of a bombing that will take place tomorrow. What level of torture is permissible to attempt to discover the information?",THOUGHTFUL),
            Q("In general, in your city, who has it worse - men or women?",EDGY),
            Q("Do you feel like it's plausible that 'slutty empowerment' is something men encourage so that women are more likely to say 'yes' to sex with them?",EDGY),
            Q("What’s your general opinion of education designed to help men learn how to be more seductive?",EDGY),
            Q("Can someone both be a kind person and also hold the exact opposite of your political views?",GENERIC),
            Q("If you could press the button and have everyone on the planet magically swap their physical sex for one year, would you do it and why?",THOUGHTFUL),
            Q("A girl walks by, and a man calls out, \"You look beautiful today!\" Is this catcalling?",EDGY),
            Q("Have you been involved in an open or polyamorous relationship? If yes with whom, and what were the terms? If not, would you consider it?",SEXY),
            Q("Do you consider 'being at peace' to be the same thing as 'being happy'?",THOUGHTFUL),
            Q("If you could become agelessly immortal, frozen at your physical prime, but you can only die once every other human is dead — would you?",THOUGHTFUL),
            Q("Do you object to male circumcision?",EDGY),
            Q("Two schools are otherwise comparable. At one school, your child would be the only member of their race, while at the other school, all students are of your child's race. Which school would you send your child to?",EDGY),
            Q("What are your coping mechanisms for stress?",SAD),
            Q("Have you ever had a one night stand? If so, what were the circumstances?",SEXY),
            Q("Are yelling fights in relationships more typical/inevitable, or terrible/avoidable?",GENERIC),
            Q("How do your personal morals differ from society’s morals?",THOUGHTFUL),
            Q("In one room, a child is about to die. In the other room, an evil demon is about to revert global ideas about gender roles to those of the United States in the 1950s. You can either save the child or kill the demon, but not both. Which do you choose?",THOUGHTFUL),
            Q("Over the entire course of recorded human history, on a large abstract scale, are humans in general behaving morally worse or better?",THOUGHTFUL),
            Q("Does supporting Trump automatically make someone an asshole?",EDGY),
            Q("Do experience the \"porn spiral + regret\"? As in - you open an increasingly weirder series of porn tabs while masturbating, and then after orgasm, immediately panic-close all of them out of shame?",SEXY),
            Q("What was your biggest financial mistake?",SAD),
            Q("Do you feel 'being beautiful' counts as an unfair advantage in life?",THOUGHTFUL),
            Q("How much money would be enough for you to kill a bag of seven kittens with a mallet?",THOUGHTFUL),
            Q("If you press the button, the top 1% of income earners in the world will be forced to pay 99% of their income to everyone else proportionally according to need. Do you press the button?",EDGY),
            Q("What do you still owe someone an apology for?",SAD),
            Q("What would you most like to change about your appearance?",SAD),
            Q("What's the worst physical pain you've experienced?",SAD),
            Q("Are you more concerned with improving the world or improving yourself?",GENERIC),
            Q("In one room, a child is about to die. In the other room, an evil demon is about to set the maximum legal (and enforced) speed limit to 45mph (72 km/h) across the globe. You can either save the child or kill the demon, but not both. Which do you choose?",THOUGHTFUL),
            Q("There are two buttons. One button kills a child who sits in the next room. The other button magically prevents anybody from drinking alcohol ever again. Which button do you press?",THOUGHTFUL),
            Q("Would you press a button that doubled your IQ?",THOUGHTFUL),
            Q("Would you support the ability of parents to genetically modify their children in order to increase intelligence and attractiveness?",THOUGHTFUL),
            Q("Are there any viewpoints so offensive that they deserve to be shut down or suppressed?",EDGY),
            Q("If someone isn't sexually attracted to people of a certain race, is this racist?",EDGY),
            Q("If there were zero social repercussions for saying offensive words, would you say them more often?",EDGY),
            Q("Would you support a political system where person's vote was weighted by their intelligence (or a score that combines several different types of intelligence)?",EDGY),
            Q("10 years ago, where did you want to be in 10 years?",GENERIC),
            Q("Can you make your ears roar/rumble by contracting that one muscle inside your head?",GENERIC),
            Q("If some men are doctors, and some doctors are tall, then does it follow that some men are tall?",THOUGHTFUL),
            Q("There is a button before you. If you press it, the entire world loses the enchantment it feels when looking at super beautiful faces. Everyone can still see and recognize faces, but all faces feel equally attractive. Would you press the button?",THOUGHTFUL),
            Q("Are you afraid of death?",SAD),
            Q("How do you heal from painful experiences? How do you know when you're done healing?",SAD),
            Q("In what ways have you been treated unfairly or unequally?",SAD),
            Q("What's the most embarrassed you've ever been?",SAD),
            Q("Who last broke up with you and why?",SAD),
            Q("Have you ever been involved in a threesome or more?",SEXY),
            Q("An attractive female teacher has sex with a 14 year old male student, and an attractive male teacher has sex with a 14 year old female student. Which is more traumatic?",UNCLASSIFIED),
            Q("How do you feel about gun control? How do you predict the person nearest you feels about gun control?",EDGY),
            Q("Regardless of your conscious beliefs or actions - subconsciously, does your gut feel like it's degrading when someone does sex work?",EDGY),
            Q("Do you have any political or social opinions that you’re afraid to express out loud to your friends?",THOUGHTFUL),
            Q("What stereotype really is accurate?",EDGY),
            Q("What experience, though difficult or painful, would you recommend to everyone?",SAD),
            Q("What habit do you have that conflicts with your values?",SAD),
            Q("What is your biggest obstacle towards happiness?",SAD),
            Q("What is your greatest insecurity?",SAD),
            Q("Are there any thoughts so offensive that you would advocate shaming those who think them (given that they don't act on those thoughts)?",THOUGHTFUL),
            Q("Do you ever enjoy the experience of emotional pain?",THOUGHTFUL),
            Q("Do you feel that you have conscious control over your beliefs? Could you, right now, decide to believe something else if you tried? If so, which beliefs?",THOUGHTFUL),
            Q("Which belief that you hold would be the most difficult to change, even in the face of overwhelming evidence?",THOUGHTFUL),
            Q("On planet A, everyone’s 30% dumber, and you’re a genius by comparison. On planet B, everyone’s 30% smarter, and you’re an idiot by comparison. You stay the same. Which planet would you prefer to live on?",THOUGHTFUL),
            Q("Of all the beliefs you hold, which will be most likely to be considered barbaric in 150 years?",THOUGHTFUL),
            Q("Would you prefer to date someone with 20 IQ points higher or 5 points lower than you?",THOUGHTFUL),
            Q("Do women have any systemic privilege due to their gender?",EDGY),
            Q("If you had to press a button and eliminate 1 million people from one standard demographic (such as age, race, location, gender), which would it be?",EDGY),
            Q("Would you rather have accidentally killed someone, or be a nonoffending pedophile?",EDGY),
            Q("In what ways do you tend to fail at communication?",SAD),
            Q("What about yourself have you been trying to fix for a long time?",SAD),
            Q("What's the most sick (mental or physical) you've ever been?",SAD),
            Q("After you poop, on average, how many times do you have to wipe before you're done?",GENERIC),
            Q("Could you have a serious relationship with someone who expressed that they thought they were unworthy of the relationship?",GENERIC),
            Q("If you had to name one thing you want that drives all your other wants, what would it be?",THOUGHTFUL),
            Q("If you press the button, all living humans instantly gain immortality, but lose the ability to have children. Do you press it?",THOUGHTFUL),
            Q("Is bestiality wrong? Are you a vegan?",THOUGHTFUL),
            Q("What do you think enlightenment is?",THOUGHTFUL),
            Q("In a world where prostitution becomes totally legal and regulated, should sex workers be allowed to deny clients based on race?",EDGY),
            Q("Would you advocate socially shaming white people who express that they are proud of being white?",EDGY),
            Q("Imagine everyone you loved died right now. You get to go back in time and talk to one of them before they die. Who would it be, and what would you say?",SAD),
            Q("To what extent have you contemplated suicide?",SAD),
            Q("You find out your crush messages people more boring/ugly/dumb than you on dating sites. Does this reduce your attraction to them?",THOUGHTFUL),
            Q("You have the option of moving to one of two cities. In Omelas, 99% of people have 10/10 life quality, while the remaining 1% have 0/10 life quality. In Bergeron, everyone has 5/10 life quality. Which city do you move to?",THOUGHTFUL),
            Q("What percentage of your preferred age/gender demographic would you be down to have sex with after roughly an hour of flirting?",UNCLASSIFIED),
            Q("Given a world where the technology makes it possible: Would you support the ability of a woman to choose to have an abortion because genetic testing has revealed that her fetus will resemble too much a racial group that she dislikes?",EDGY),
            Q("Given the guarantee that nobody will ask you the question: What is a question that you would refuse to answer?",THOUGHTFUL),
            Q("What's the most controversial opinion you hold among your own social group?",THOUGHTFUL),
            Q("In a world where different ethnicities had strong genetic differences which caused different moral behavior, would racism be okay or still not okay?",EDGY),
            Q("Would you rather be raped or falsely (but convincingly) accused of rape?",EDGY),
            Q("How have you most disappointed your parents?",SAD),
            Q("If you had to fuck a cow, would you rather it be dead or alive?",EDGY),
            Q("What was the single most difficult thing you've ever had to do?",SAD),
            Q("What's the worst emotional pain you've experienced?",SAD),
            Q("When was the last time you cried? What was it about?",SAD),
            Q("Do any naked pictures of yourself exist? If yes, where are they and who has access to them?",SEXY),
            Q("If everyone’s stats were displayed above their head at all times (intelligence, charisma, dexterity, etc.), would you be treated better or worse?",THOUGHTFUL),
            Q("If you could press the button that would automatically erase every single false belief you have, would you do it?",THOUGHTFUL),
            Q("If all sexism were magically and totally eliminated, would gender ratio of all jobs, ideologies, and communities reach 50/50?",EDGY),
            Q("Is there anything which arouses you that you've never admitted to anybody?",SEXY),
            Q("Does a straw have one hole or two holes?",GENERIC),
            Q("Does astrology hold predictive power?",GENERIC),
            Q("Have you been loved enough?",GENERIC),
            Q("Have you tried psychedelics?",GENERIC),
            Q("If the people in the room were arranged on a spectrum from least to most attractive, which two people would you be between?",GENERIC),
            Q("What is the best advice you've been given, and why did you need it?",GENERIC),
            Q("What problems do you see in other people’s relationships?",GENERIC),
            Q("What viewpoint is the most difficult for you to empathize with?",GENERIC),
            Q("What was the most significant thing you’ve ever changed your mind about?",GENERIC),
            Q("When you feel an emotion, how often does it involve a physical bodily sensation in addition to a mental state?",GENERIC),
            Q("Would you rather change genders every time you sneeze, or be unable to tell the difference between babies and muffins?",GENERIC),
            Q("If you could see one measurement or statistic over everyone's heads, what would you want it to indicate?",UNCLASSIFIED),
            Q("In what ways don't you trust yourself?",UNCLASSIFIED),
            Q("Would you rather a dangerous rapist go free or an innocent man be criminally punished for rape?",UNCLASSIFIED),
            Q("Have you named your genitals?",SEXY),
            Q("How easy is it for you to have an orgasm?",SEXY),
            Q("In total, have you given or received more oral sex?",SEXY),
            Q("What unusual trait do you find most attractive in a romantic partner?",SEXY),
            Q("What's the wildest/most unusual thing you've ever done in bed?",SEXY),
            Q("Who in this room would you most like to have sex with?",SEXY),
            Q("Would you rather blow your mind or load?",SEXY),
            Q("Would you rather have sex with someone 10 years younger than you or 5 years older?",SEXY),
            Q("How do you feel about being naked in front of friends?",GENERIC),
            Q("If you could ask every single person in the world one question, what would you ask?",GENERIC),
            Q("If you could have one but not the other, would you rather love someone or be loved by someone?",GENERIC),
            Q("In general, you feel like your destiny is to be more of a hero or sidekick?",GENERIC),
            Q("Is success due more to hard work or luck?",GENERIC),
            Q("What are the signs that someone really understands you, uniquely?",GENERIC),
            Q("What has been your biggest act of compassion?",GENERIC),
            Q("Which group is larger: people who trust you, or people you trust?",GENERIC),
            Q("Which has helped you more in life, your looks or intelligence?",GENERIC),
            Q("Who in the room right now do you admire the most?",GENERIC),
            Q("Would you rather lose the ability to jump or to swim?",GENERIC),
            Q("Would you rather double the amount of emotional pain and pleasure you feel on a daily basis, or cut both in half?",GENERIC),
            Q("Would you rather increase the amount that people respect you, or desire you?",GENERIC),
            Q("Would you rather lose the ability to sing or to swear?",GENERIC),
            Q("Would you rather spend the rest of your life with one lover, but no friends; or with many friends, but no lovers?",GENERIC),
            Q("A 14 year old has sex. How large does the age gap have to be between the 14 year old and their partner before the child can no longer meaningfully consent to sex?",UNCLASSIFIED),
            Q("Does modern western culture encourage women to either overreact or underreact to \"minor\" sexual assaults, such as groping, too-drunk sex, etc.?",UNCLASSIFIED),
            Q("Generally speaking, have jews or black people experienced greater oppression throughout history?",UNCLASSIFIED),
            Q("What aspect about the person to your left, gives you the strongest negative feeling?",UNCLASSIFIED),
            Q("What do you most admire about the person to your right?",UNCLASSIFIED),
            Q("What would you do if you had Bill Gates' money?",UNCLASSIFIED),
            Q("Have you masturbated today? When was the last time you masturbated?",SEXY),
            Q("If you could press a button and double the sex drive of all women on earth, would you do it?",SEXY),
            Q("If you had to choose one, would you rather double or halve your sex drive?",SEXY),
            Q("If you tried, could you list the names of everyone you've had sex with?",SEXY),
            Q("If you woke up to a 10/10 hot stranger of your desired sex performing oral on you (without asking), would you feel positively or negatively?",SEXY),
            Q("Of the things you've done sexually, what has made you the most uncomfortable?",SEXY),
            Q("What's your relationship to buttplugs?",SEXY),
            Q("Would you ever have sex with someone you're not really that attracted to, if they were down for having sex with you? (given: you're available, you're aroused/ready to be aroused, etc.)",SEXY),
            Q("Do you own any cryptocurrency? (Bitcoin, ethereum, litecoin, etc...)",GENERIC),
            Q("Do you wipe your butt primarily while sitting or standing?",GENERIC),
            Q("Have you ever dated someone who you felt was below your standards?",GENERIC),
            Q("Have you ever had (what you consider to be) a spiritual experience?",GENERIC),
            Q("How boring are you?",GENERIC),
            Q("Is pee stored in the balls?",GENERIC),
            Q("What about your past are you most ashamed of?",GENERIC),
            Q("What groups or communities are you most judged for being a member of?",GENERIC),
            Q("What kind of people do you get along best with?",GENERIC),
            Q("What was your embarrassing high school phase?",GENERIC),
            Q("What’s the worst crime you’ve committed?",GENERIC),
            Q("When have you been treated differently because of your race?",GENERIC),
            Q("Who do you hate most?",GENERIC),
            Q("Would you rather magically gain the ability to fall instantly asleep whenever you want, or wake up easily and full of energy?",GENERIC),
            Q("Generally speaking, is it more pleasant or unpleasant when interacting with someone who wants to have sex with you, but you don't want to have sex with them?",UNCLASSIFIED),
            Q("How often does pooping feel great?",UNCLASSIFIED),
            Q("What talents have you developed accidentally?",UNCLASSIFIED),
            Q("Would you be willing to show your browsing history to everybody present? What if this didn't include porn?",UNCLASSIFIED),
            Q("Would you rather date someone who's an enthusiastic fan of astrology, or Donald Trump?",UNCLASSIFIED),
            Q("How do you feel about anal sex?",SEXY),
            Q("What was your most disappointing sexual experience?",SEXY),
            Q("When women say 'daddy' in a sexual context, do you find it more creepy or hot?",SEXY),
            Q("Which would have more volume if you liquified and poured it into a glass - your balls or your penis?",SEXY),
            Q("Do you currently follow the same faith tradition of your parents?",GENERIC),
            Q("Have you ever been arrested? If not, how close have you come?",GENERIC),
            Q("If there were a way to painlessly and permanently alter the thoughts of a person you know, who and what would you change?",GENERIC),
            Q("If you died and got to be reborn right now, in the same city, you would choose to be born a man or woman?",GENERIC),
            Q("In the last 10 years, have you ever gone an entire day without putting on any clothes?",GENERIC),
            Q("Should we give a posthumous medal to the guy who killed hitler?",GENERIC),
            Q("What is the coolest fact about yourself that few people know?",GENERIC),
            Q("What personality trait are you most proud of?",GENERIC),
            Q("What words or behaviors really offend you?",GENERIC),
            Q("What's the craziest drug experience you've had?",GENERIC),
            Q("When you make a typo, do you tend to delete the entire word and start over, or backspace exactly to the typo?",GENERIC),
            Q("Which accomplishment are you most proud of?",GENERIC),
            Q("Who is the smartest person you personally know?",GENERIC),
            Q("You must visit a museum. Would you rather see an art or a history musem?",GENERIC),
            Q("All women are arranged before you on a spectrum of those who never wear makeup to those who always wear makeup. You must press a button and eliminate either the bottom 25% or the top 25% (your loved ones are safe regardless). Which end of the spectrum do you destroy?",UNCLASSIFIED),
            Q("If you could ask the universe one question and get the absolute truth, what would you want to know?",UNCLASSIFIED),
            Q("Which group - unattractive women, attractive women, unattractive men, or attractive men - would benefit the most from social justice/radical feminist/far left ideas?",UNCLASSIFIED),
            Q("Have you ever had  times with someone who never performed oral sex on you?",SEXY),
            Q("If you were a sex toy, what sex toy would you be?",SEXY),
            Q("Do you remember learning how to read?",GENERIC),
            Q("Have you ever gotten a rash from poison ivy?",GENERIC),
            Q("Have you ever seen a message broadcast in a public place along the lines of \"You are beautiful!\" or \"You are worthwhile!\" or \"Things will get better!\" that made you feel better about yourself?",GENERIC),
            Q("Have you ever thrown up inside a car?",GENERIC),
            Q("When your hands are dry, can you make them sweat just by thinking?",GENERIC),
            Q("Who in your family do you get along the worst with?",GENERIC)
        )

        fun randomQuestions(n: Int): List<Question> {
            return questions
                .shuffled()
                .subList(0,n)
                .map(::makeQuestion)
        }

        fun createQuestions(): List<Question> {
            return questions
                .subList(0,10)
                .map(::makeQuestion)
        }

        private fun makeQuestion(q: Q): Question {
            return Question(Random.Default.nextLong(), q.text, q.type)
        }
    }
}